# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-10 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_flashcard_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='subject',
            field=models.CharField(max_length=30),
        ),
    ]
