# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-10 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20200610_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='subject',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='subject',
            field=models.ManyToManyField(to='App.Subject'),
        ),
    ]
