# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-10 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20200610_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject',
            field=models.CharField(max_length=30),
        ),
    ]
