# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-10 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_auto_20200610_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Subject'),
        ),
    ]
